### ISSUE TITLE
Nom del projecte

### ISSUE THREAD

**Issue by dolorssala** [YumaIshigooka/G22-Software#2]
Podeu si us plau posar el vostre G2x- (on x sigui el valor del vostre grup) davant del nom del projecte?
Per nosaltres poder-los identificar i visualitzar en ordre alfabètic.

L'he assignat a algú diferent, perquè es practiqui.
Qui ho faci cal que tanqui el issue.

Gràcies
Dolors

**Comment by YumaIshigooka** [comment]
Arreglat
