### ISSUE TITLE
Creación y Compartición del Proyecto

### ISSUE THREAD

**Issue by YumaIshigooka** [YumaIshigooka/G22-Software#3]
Contestad si habeis podido clonar el repositorio con éxito, o si ha habido problemas (explicando este).

**Comment by YumaIshigooka** [comment]
<img width="548" alt="cmd_BjDS2LYa9t" src="https://github.com/YumaIshigooka/Software-G22/assets/114680656/f83cc3a4-b903-4fd8-8c8b-d9c8c89715c9">

**Comment by stanciuantonio** [comment]
<img width="513" alt="SCR-20240517-nrdb" src="https://github.com/YumaIshigooka/Software-G22/assets/123732933/b7cbef02-b36f-47b1-8c40-609b7ab6d8da">

**Comment by AlexSalas55** [comment]
![Captura de pantalla 2024-05-20 205008](https://github.com/YumaIshigooka/Software-G22/assets/50219007/a7e06fd7-7248-4916-9ba3-bd0a3c1fed12)

**Comment by vicens-aniol** [comment]
![image](https://github.com/YumaIshigooka/Software-G22/assets/31472364/6fd8be28-d058-4976-9708-b4c0897d114f)

**Comment by FerranHoms** [comment]
![image](https://github.com/YumaIshigooka/Software-G22/assets/114679976/f948e1d6-34bd-41da-9e07-48aee0d6eddf)

**Comment by FerranHoms** [comment]
<img width="530" alt="image" src="https://github.com/YumaIshigooka/Software-G22/assets/114679976/63931e90-264f-4bbc-877b-641db67d7b8c">

**Comment by RubenCastanoGomez** [comment]
![Captura de pantalla 2024-05-26 000406](https://github.com/YumaIshigooka/G22-Software/assets/131852950/3a497815-2eb2-4906-a099-858ab298df97)

**Comment by sergirivet** [comment]
![image](https://github.com/YumaIshigooka/G22-Software/assets/170340625/92be4d1f-ffaf-4ac9-a565-f237fa14dac0)

**Comment by rebollocarla** [comment]
![Captura de pantalla 2024-05-26 151618](https://github.com/YumaIshigooka/G22-Software/assets/92046266/85de4073-5497-4c04-b279-471feb36755c)

**Comment by Gerandez** [comment]
![image](https://github.com/YumaIshigooka/G22-Software/assets/131766879/232bad88-1c1b-4bd9-983e-cf70a3a4e79f)
